# Generated by Django 3.0.5 on 2020-12-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome', max_length=100)),
                ('email', models.TextField(db_column='email', max_length=100)),
                ('wishlist', models.CharField(db_column='wishlist', max_length=1000)),
            ],
        ),
    ]
