# Generated by Django 3.0.5 on 2020-12-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientWishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='client',
            name='unique_wishlist',
            field=models.TextField(blank=True, db_column='unique_wishlist', max_length=1000),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(db_column='product_id', max_length=1000)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientWishlist.Client')),
            ],
        ),
    ]
