# Generated by Django 3.0 on 2020-12-21 00:18

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clientWishlist', '0002_auto_20201218_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='id',
        ),
        migrations.AddField(
            model_name='client',
            name='id_client',
            field=models.UUIDField(default=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product_id',
            field=djongo.models.fields.JSONField(),
        ),
    ]
